#! /bin/sh

terminate()
{
	poweroff
}

SERVER='isil'
MSM='/usr/local/bin/msm'
CONNECTED=$($MSM $SERVER connected )
COUNT_FILE=/tmp/server_empty_since
RETRIES=15
if [ "$CONNECTED" == "No players are connected." ]; then
	echo $(($(cat ${COUNT_FILE} 2>/dev/null)+1)) > ${COUNT_FILE}
	[[ $(cat ${COUNT_FILE}) -ge ${RETRIES} ]] && terminate
else
	echo 0 > ${COUNT_FILE}
fi

