#! /bin/sh

if [ -f /etc/environment ]; then
    while read LINE
    do
        export $LINE
    done < /etc/environment
fi

SERVER='isil'
MSM='/usr/local/bin/msm'

$MSM $SERVER save off
$MSM $SERVER save all
sleep 5
$MSM $SERVER worlds todisk
sleep 5

AWS_DEFAULT_REGION=$(aws --output text s3api get-bucket-location --bucket $MSM_S3_BUCKET)
tar czf /tmp/backup.tgz /opt/msm/jars /opt/msm/versioning /opt/msm/servers
aws --region $AWS_DEFAULT_REGION s3 cp /tmp/backup.tgz s3://$MSM_S3_BUCKET/

$MSM $SERVER save on

